[runs]
git-tree-sha1 = "fc6b445006756ba622e6dcdcefc8fcd835945459"
lazy = true

    [[runs.download]]
    sha256 = "e21ada9efea401bc6f95b0f896452993e4c1de48d24810db1bf011b43152bde4"
    url = "https://s3.eu-central-1.amazonaws.com/vision-group-file-sharing/Data%20backup%20and%20storage/Claudia/SisyphusCooperation/runs.csv.tar.gz"

[tracks]
git-tree-sha1 = "b03796ad46732b2d03f1d0894847302b118570ff"
lazy = true

    [[tracks.download]]
    sha256 = "248317ac2b43ff679ca39d1d3228c3e297a0db1b84705d573e9e664b69b9e04b"
    url = "https://s3.eu-central-1.amazonaws.com/vision-group-file-sharing/Data%20backup%20and%20storage/Claudia/SisyphusCooperation/tracks.tar.gz"
